version: '3,8'
services:
  mongo:
    container_name: GymRecorder-mongo
    image: mongo:4
    restart: no
    environment:
      MONGO_DATA_DIR: /data/db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  postgres:
    container_name: GymRecorder-postgres
    image: postgres:16
    restart: no
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: GymRecorder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  mongo-data:
  postgres-data: