spring:
  application:
    name: GymRecorder

  data:
    mongodb:
      host: localhost
      port: 27017
      database: GymRecorder

  datasource:
    url: jdbc:postgresql://localhost:5432/GymRecorder
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enable: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true